### ISSUE TITLE
UI: DPS meter — floating damage-per-second display

### ISSUE THREAD

**Issue by ApprenticeGC** [GiantCroissant-Lunar/vampire-mini-build#218]
## Task

Create a DPS (damage-per-second) meter that tracks the player's damage output over a rolling window and displays it as a floating HUD element.

## Files to Create

- `project/hosts/complete-app/Scripts/UI/DpsMeter.cs`

### Class: `DpsMeter`
- Inherits `Label` (Node2D with a Label child is also acceptable as a single-file solution)
- Namespace: `VampireMini`

### Exports
```csharp
[Export] public float WindowSeconds { get; set; } = 3.0f;  // rolling window
[Export] public NodePath PlayerPath { get; set; }
```

### Behavior
- Maintain a `List<(float time, float damage)>` queue of damage events
- Expose a `public void RegisterHit(float damage)` method that other systems call
- In `_Process(double delta)`:
  - Get current time using `Time.GetTicksMsec() / 1000.0f` (NOT `GetTree().Time` — that does not exist in Godot 4.6 C#)
  - Prune entries older than `WindowSeconds` from the front of the queue
  - Compute DPS = sum of damages in queue / `WindowSeconds`
  - Update `Text` to `$"DPS: {dps:F0}"`
- Position: top-right corner of viewport (use `GetViewportRect().Size`)
- Hide when DPS is 0 (no hits in window)

### Integration note
The method `RegisterHit(float damage)` will be wired up externally; no modification of existing files is needed.

## ⚠️ Common Pitfalls

- **CRITICAL: Use `Time.GetTicksMsec() / 1000.0f` for current time** — `GetTree().Time` does NOT exist in Godot 4.6 C# and will cause a compile error CS1061
- Float literals need `f` suffix: `3.0f`, not `3.0`
- Use `Mathf.Max()` not `Math.Max()`
- Cast `delta` to `float` where needed: `(float)delta`
- Do NOT modify existing files or `.csproj`
- Keep all code in the one new file

## Rules

- New files only — do not modify any existing file
- All code must compile with `dotnet build` under Godot 4.6 C# (.NET 8)
- No external dependencies
- Follow existing namespace `VampireMini`
